#![allow(deprecated)]

#[cfg(target_os = "macos")]
use cocoa::base::{id, nil};
#[cfg(target_os = "macos")]
use libc::c_char;
#[cfg(target_os = "macos")]
use objc::{class, msg_send, sel, sel_impl};

#[derive(Clone, Debug)]
pub struct PasteboardTypeData {
    pub type_name: String,
    pub data: Vec<u8>,
}

#[derive(Clone, Debug)]
pub struct PasteboardItemSnapshot {
    pub entries: Vec<PasteboardTypeData>,
}

#[derive(Clone, Debug, Default)]
pub struct PasteboardSnapshot {
    pub items: Vec<PasteboardItemSnapshot>,
}

#[cfg(target_os = "macos")]
fn nsstring_to_string(s: id) -> Option<String> {
    if s == nil {
        return None;
    }
    let c_str: *const c_char = unsafe { msg_send![s, UTF8String] };
    if c_str.is_null() {
        return None;
    }
    Some(
        unsafe { std::ffi::CStr::from_ptr(c_str) }
            .to_string_lossy()
            .into_owned(),
    )
}

#[cfg(target_os = "macos")]
fn string_to_nsstring(text: &str) -> id {
    let ns: id = unsafe { msg_send![class!(NSString), alloc] };
    unsafe {
        msg_send![
            ns,
            initWithBytes: text.as_ptr()
            length: text.len()
            encoding: 4usize // NSUTF8StringEncoding
        ]
    }
}

#[cfg(target_os = "macos")]
fn bytes_to_nsdata(bytes: &[u8]) -> id {
    unsafe {
        msg_send![
            class!(NSData),
            dataWithBytes: bytes.as_ptr()
            length: bytes.len()
        ]
    }
}

#[cfg(target_os = "macos")]
pub fn snapshot_general_pasteboard() -> Result<PasteboardSnapshot, String> {
    let pb: id = unsafe { msg_send![class!(NSPasteboard), generalPasteboard] };
    if pb == nil {
        return Err("NSPasteboard.generalPasteboard is nil".to_string());
    }
    let items: id = unsafe { msg_send![pb, pasteboardItems] };
    if items == nil {
        return Ok(PasteboardSnapshot::default());
    }

    let count: usize = unsafe { msg_send![items, count] };
    let mut snapshot = PasteboardSnapshot::default();

    for idx in 0..count {
        let item: id = unsafe { msg_send![items, objectAtIndex: idx] };
        if item == nil {
            continue;
        }
        let types: id = unsafe { msg_send![item, types] };
        if types == nil {
            continue;
        }
        let type_count: usize = unsafe { msg_send![types, count] };
        let mut entries = Vec::new();

        for t_idx in 0..type_count {
            let t: id = unsafe { msg_send![types, objectAtIndex: t_idx] };
            let Some(type_name) = nsstring_to_string(t) else {
                continue;
            };
            let data: id = unsafe { msg_send![item, dataForType: t] };
            if data == nil {
                continue;
            }
            let len: usize = unsafe { msg_send![data, length] };
            let ptr: *const u8 = unsafe { msg_send![data, bytes] };
            if ptr.is_null() || len == 0 {
                continue;
            }
            let bytes = unsafe { std::slice::from_raw_parts(ptr, len) }.to_vec();
            entries.push(PasteboardTypeData {
                type_name,
                data: bytes,
            });
        }

        snapshot.items.push(PasteboardItemSnapshot { entries });
    }

    Ok(snapshot)
}

#[cfg(target_os = "macos")]
pub fn write_transient_text_for_paste(text: &str) -> Result<(), String> {
    let pb: id = unsafe { msg_send![class!(NSPasteboard), generalPasteboard] };
    if pb == nil {
        return Err("NSPasteboard.generalPasteboard is nil".to_string());
    }

    let _: isize = unsafe { msg_send![pb, clearContents] };

    let item: id = unsafe { msg_send![class!(NSPasteboardItem), new] };
    if item == nil {
        return Err("NSPasteboardItem allocation failed".to_string());
    }

    let text_type = string_to_nsstring("public.utf8-plain-text");
    let text_value = string_to_nsstring(text);
    let text_ok: bool = unsafe { msg_send![item, setString: text_value forType: text_type] };
    if !text_ok {
        return Err("failed to set text for pasteboard item".to_string());
    }

    // History apps that respect these markers may skip storing this item.
    for marker in [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ] {
        let marker_type = string_to_nsstring(marker);
        let marker_value = string_to_nsstring("1");
        let _: bool = unsafe { msg_send![item, setString: marker_value forType: marker_type] };
    }

    let arr: id = unsafe { msg_send![class!(NSMutableArray), array] };
    unsafe {
        let _: () = msg_send![arr, addObject: item];
    }
    let write_ok: bool = unsafe { msg_send![pb, writeObjects: arr] };
    if !write_ok {
        return Err("failed to write transient item to pasteboard".to_string());
    }
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn restore_general_pasteboard(snapshot: &PasteboardSnapshot) -> Result<(), String> {
    let pb: id = unsafe { msg_send![class!(NSPasteboard), generalPasteboard] };
    if pb == nil {
        return Err("NSPasteboard.generalPasteboard is nil".to_string());
    }

    let _: isize = unsafe { msg_send![pb, clearContents] };
    if snapshot.items.is_empty() {
        return Ok(());
    }

    let arr: id = unsafe { msg_send![class!(NSMutableArray), array] };
    for item in &snapshot.items {
        let pb_item: id = unsafe { msg_send![class!(NSPasteboardItem), new] };
        if pb_item == nil {
            continue;
        }
        for entry in &item.entries {
            let ns_type = string_to_nsstring(&entry.type_name);
            let ns_data = bytes_to_nsdata(&entry.data);
            let _: bool = unsafe { msg_send![pb_item, setData: ns_data forType: ns_type] };
        }
        unsafe {
            let _: () = msg_send![arr, addObject: pb_item];
        }
    }

    let write_ok: bool = unsafe { msg_send![pb, writeObjects: arr] };
    if !write_ok {
        return Err("failed to restore snapshot to pasteboard".to_string());
    }
    Ok(())
}

#[cfg(not(target_os = "macos"))]
pub fn snapshot_general_pasteboard() -> Result<PasteboardSnapshot, String> {
    Ok(PasteboardSnapshot::default())
}

#[cfg(not(target_os = "macos"))]
pub fn write_transient_text_for_paste(_text: &str) -> Result<(), String> {
    Err("macOS only".to_string())
}

#[cfg(not(target_os = "macos"))]
pub fn restore_general_pasteboard(_snapshot: &PasteboardSnapshot) -> Result<(), String> {
    Err("macOS only".to_string())
}
